### ISSUE TITLE
remember user not working 

### ISSUE THREAD

**Issue by monikarora** [paypal/paypal-here-sdk-android-distribution#121]
Hey @amrish7 , i want to save user name & user password , but if i kill app data is remove

String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_SANDBOX;

//String CONFIG_ENVIRONMENT = PayPalConfiguration.ENVIRONMENT_NO_NETWORK/

private static PayPalConfiguration config = new PayPalConfiguration()
.environment(CONFIG_ENVIRONMENT)
.clientId(CONFIG_CLIENT_ID)
.rememberUser(true)

**Comment by amrish7** [comment]
It could be by design. 

If I am not mistaken, the `PayPalConfiguration` object sits in the https://github.com/paypal/PayPal-Android-SDK repository (not this one) and `com.paypal.android.sdk.payments.PayPalConfiguration` namespace. 

Do you want me to move this issue to [PayPal-Android-SDK](https://github.com/paypal/PayPal-Android-SDK) repository?

**Comment by amrish7** [comment]
@ppmtscory Could you add your thoughts on this issue?

**Comment by monikarora** [comment]
Okay @amrish7 
yes already added this issue in PayPal-Android-SDK repository , but still response for him

**Comment by ppmtscory** [comment]
Yes, that is for a different SDK and will need to be answered by the folks that support that issue.  You should receive an answer on that issue over on that repo.
