### ISSUE TITLE
Clear reader screen after transaction complete

### ISSUE THREAD

**Issue by JarredSteenvoorden** [paypal/paypal-here-sdk-android-distribution#65]
After taking an EMV payment with the processPaymentWithSDKUI() function and choosing a receipt option they PayPay Here screen remains with the display either:
"$1.00 paid. Thank you!"
"$1.00 Transaction cancelled"

Is there a function to call to reset the display back to the original:
"Ready to accept payments."

I see that in #41 there is the suggestion to initiate a reconnect however It would be a much smoother experience if we could simply clear the display.

Is there any function of the SDK to do this?

Also not as important but is it possible to show custom text on the readers display?

**Comment by ppmtscory** [comment]
After the transaction completes, if you simply call `beginPayment()` again, that should clear the reader as well and set it back to the Ready to Accept Payments screen.  As for custom text, no, there's currently no way to add custom text to the reader.

**Comment by jarred-s** [comment]
This doesn't seem to be working, after a successful payment calling beginPayment() does not clear the display, it remains with the "$1.00 paid. Thank you!" text until processPaymentWithSDKUI() is called and the "Tap, Insert, or Swipe" is shown.

Can you confirm if this is a bug or if there is another way to get back to the "Ready to Accept Payments" screen.

**Comment by ppmtscory** [comment]
That should work.  Let me do some research and playing around with the sample app prior to confirming if this is a bug or not.  I will update you here once I'm finished.

**Comment by ppmtscory** [comment]
@jarred-s so after some testing, and help from the dev team, I've found that you need to add an item (can be $0) to the invoice that's created with `beginPayment`.  This will reset the reader screen to Ready to Accept Payments.  We understand that having to add the actual item instead of just a new blank transaction isn't ideal, so we've added it to our backlog of work to be fixed.  Below is the snippet of code that I added to the sample app to validate this.  What I did was call `clearAllItems()` immediately after so that I didn't forget about a rogue $0 item attached to my payment.  You can then add items or modify your created invoice as you see fit prior to processing your payment.
```
        Invoice newInv = PayPalHereSDKWrapper.getInstance().beginPayment(BigDecimal.ZERO);
        InvoiceItem newItem = DomainFactory.newInvoiceItem("item 1", "item 1", BigDecimal.ZERO);
        newInv.addItem(newItem, BigDecimal.ZERO);
        newInv.clearAllItems();
```
Let us know if you have any further questions.

**Comment by ppmtscory** [comment]
A new SDK and sample app are available for use which should correct this enhancement.
